In [7]:
import numpy as np
print(np.__version__)

2.2.0


In [8]:
null_vector = np.zeros(10)
print(null_vector)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
arr = np.array([1, 2, 3])
print(arr.nbytes)  # in Bytes


24


In [10]:
python -c "import numpy as np; help(np.add)"


SyntaxError: invalid syntax (4208605629.py, line 1)

In [11]:
vector = np.zeros(10)
vector[4] = 1
print(vector)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [12]:
vector = np.arange(10, 50)
print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [13]:
vector = np.arange(10, 50)
reversed_vector = vector[::-1]
print(reversed_vector)


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [14]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [15]:
arr = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(arr)
print(non_zero_indices)


(array([0, 1, 4]),)


In [16]:
random_array = np.random.random((3, 3, 3))
print(random_array)


[[[0.66149321 0.04855622 0.9621175 ]
  [0.36008882 0.85838859 0.60630724]
  [0.44715721 0.37824327 0.11754865]]

 [[0.06186188 0.17389723 0.59278105]
  [0.56451487 0.69611639 0.85194152]
  [0.21136802 0.08053025 0.51435864]]

 [[0.46510928 0.84119352 0.63317521]
  [0.09149598 0.21664303 0.00340383]
  [0.65708258 0.97842826 0.03917545]]]


In [22]:
random_vector = np.random.random(30)
mean_value = random_vector.mean()
print(mean_value)


0.4948335125611883


In [18]:
matrix = np.ones((5, 5))
matrix[1:-1, 1:-1] = 0
print(matrix)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [23]:
arr = np.array([[1, 1], [1, 1]])
bordered_arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(bordered_arr)


[[0 0 0 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 0 0 0]]


In [24]:
print(0 * np.nan)  # nan
print(np.nan == np.nan)  # False
print(np.inf > np.nan)  # False
print(np.nan - np.nan)  # nan
print(np.nan in set([np.nan]))  # True
print(0.3 == 3 * 0.1)  # False


nan
False
False
nan
True
False


In [26]:
matrix = np.zeros((5, 5))
np.fill_diagonal(matrix[1:], [1, 2, 3, 4])
print(matrix)


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [27]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [28]:
arr = np.arange(6*7*8).reshape(6, 7, 8)
index = np.unravel_index(100, arr.shape)
print(index)


(np.int64(1), np.int64(5), np.int64(4))
