In [1]:
import numpy as np
print(np.__version__)

2.1.1


In [2]:
null_vector = np.zeros(10)
print(null_vector)
random = np.random.rand(2,3,4)
print(random)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[[0.8257215  0.87244005 0.50055465 0.76753692]
  [0.28225289 0.12600452 0.96682605 0.31035366]
  [0.79246362 0.48074164 0.51223028 0.3785273 ]]

 [[0.15738202 0.92291385 0.70788295 0.30235058]
  [0.54751613 0.5192438  0.46722489 0.73837581]
  [0.81830818 0.2585091  0.54257396 0.18737089]]]


In [3]:
arr = np.array([1, 2, 3])
print(arr.nbytes)  # in Bytes


24


In [4]:
python -c "import numpy as np; help(np.add)"


SyntaxError: invalid syntax (4208605629.py, line 1)

In [ ]:
vector = np.zeros(10)
vector[4] = 1
print(vector)


In [ ]:
vector = np.arange(10, 50)
print(vector)


In [ ]:
vector = np.arange(10, 50)
reversed_vector = vector[::-1]
print(reversed_vector)


In [ ]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)


In [ ]:
arr = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(arr)
print(non_zero_indices)


In [ ]:
random_array = np.random.random((2,4))
print(random_array)


In [ ]:
random_array.reshape(4,-1)
print(random_array)

random_vector = np.random.random(30)
mean_value = random_vector.mean()
print(mean_value)


In [ ]:
matrix = np.ones((5, 5))
matrix[1:-1, 1:-1] = 0
print(matrix)


In [ ]:
arr = np.array([[1, 1], [1, 1]])
bordered_arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(bordered_arr)


In [ ]:
print(0 * np.nan)  # nan
print(np.nan == np.nan)  # False
print(np.inf > np.nan)  # False
print(np.nan - np.nan)  # nan
print(np.nan in set([np.nan]))  # True
print(0.3 == 3 * 0.1)  # False


In [ ]:
matrix = np.zeros((5, 5))
np.fill_diagonal(matrix[1:], [1, 2, 3, 4])
print(matrix)


In [6]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 2
print(checkerboard)


[[0 2 0 2 0 2 0 2]
 [1 0 1 0 1 0 1 0]
 [0 2 0 2 0 2 0 2]
 [1 0 1 0 1 0 1 0]
 [0 2 0 2 0 2 0 2]
 [1 0 1 0 1 0 1 0]
 [0 2 0 2 0 2 0 2]
 [1 0 1 0 1 0 1 0]]


In [ ]:
arr = np.arange(6*7*8).reshape(6, 7, 8)
index = np.unravel_index(100, arr.shape)
print(index)
