In [2]:
import numpy as np
print(np.__version__)

2.1.1


In [3]:
null_vector = np.zeros(10)
print(null_vector)
random = np.random.rand(2,3,4)
print(random)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[[0.10362065 0.98549679 0.69292666 0.4358948 ]
  [0.18045632 0.44187721 0.1228532  0.31208661]
  [0.43138268 0.85785213 0.35791962 0.77611685]]

 [[0.71306421 0.17134599 0.62023991 0.92207041]
  [0.0797287  0.76123189 0.68357903 0.44094687]
  [0.58917292 0.52062424 0.12389529 0.57443995]]]


In [9]:
arr = np.array([1, 2, 3])
print(arr.nbytes)  # in Bytes


24


In [10]:
python -c "import numpy as np; help(np.add)"


SyntaxError: invalid syntax (4208605629.py, line 1)

In [11]:
vector = np.zeros(10)
vector[4] = 1
print(vector)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [12]:
vector = np.arange(10, 50)
print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [13]:
vector = np.arange(10, 50)
reversed_vector = vector[::-1]
print(reversed_vector)


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [14]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [15]:
arr = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(arr)
print(non_zero_indices)


(array([0, 1, 4]),)


In [8]:
random_array = np.random.random((5,3,5,3))
print(random_array)


[[[[9.76614362e-01 5.71093855e-01 8.14493004e-01]
   [4.86785625e-01 2.25642904e-01 3.94064000e-01]
   [6.07378367e-01 4.92602286e-01 8.75531250e-01]
   [2.43730596e-01 8.80088333e-01 8.33680778e-02]
   [1.02350699e-01 5.59022628e-01 8.26769147e-01]]

  [[8.87241548e-01 3.83216532e-01 4.73669050e-01]
   [3.50253000e-01 8.80839880e-01 5.88391382e-01]
   [4.70619154e-02 4.55791667e-01 5.29764165e-01]
   [8.94448767e-01 5.33541664e-01 4.46781060e-01]
   [8.06163513e-01 2.17643704e-01 7.30903157e-01]]

  [[1.63479553e-01 1.17160336e-01 8.78123137e-01]
   [7.19743592e-01 6.94442935e-01 6.59490780e-01]
   [8.32226470e-02 7.08258135e-01 2.97079628e-01]
   [4.58678288e-01 8.64506756e-01 6.36485021e-02]
   [7.35253142e-01 9.21228425e-02 5.57730532e-01]]]


 [[[9.57654659e-01 9.41890067e-01 9.43206838e-01]
   [4.48120746e-01 5.67525454e-01 2.17075633e-02]
   [8.25117850e-01 5.93340694e-01 1.70965775e-01]
   [8.71483624e-01 6.16138077e-01 4.95609840e-01]
   [6.61356080e-01 9.72757858e-01 2.525329

In [9]:
random_array.reshape(2,3,4)
print(random_array)

random_vector = np.random.random(30)
mean_value = random_vector.mean()
print(mean_value)


ValueError: cannot reshape array of size 225 into shape (2,3,4)

In [18]:
matrix = np.ones((5, 5))
matrix[1:-1, 1:-1] = 0
print(matrix)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [23]:
arr = np.array([[1, 1], [1, 1]])
bordered_arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(bordered_arr)


[[0 0 0 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 0 0 0]]


In [24]:
print(0 * np.nan)  # nan
print(np.nan == np.nan)  # False
print(np.inf > np.nan)  # False
print(np.nan - np.nan)  # nan
print(np.nan in set([np.nan]))  # True
print(0.3 == 3 * 0.1)  # False


nan
False
False
nan
True
False


In [26]:
matrix = np.zeros((5, 5))
np.fill_diagonal(matrix[1:], [1, 2, 3, 4])
print(matrix)


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [27]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [28]:
arr = np.arange(6*7*8).reshape(6, 7, 8)
index = np.unravel_index(100, arr.shape)
print(index)


(np.int64(1), np.int64(5), np.int64(4))
